### ISSUE TITLE
xxxbiquge 书源配置问题

### ISSUE THREAD

**Issue by hillson-liu** [binbyu/Reader#105]
`{
	"book_sources":	[{
			"title":	"新新新笔趣阁",
			"host":	"http://www.xxxbiquge.me",
			"query_url":	"http://www.xxxbiquge.me/search/result.html?searchkey=%s",
			"query_method":	0,
			"query_params":	"",
			"query_charset":	0,
			"book_name_xpath":	"//div[@class='search-list']/ul/li[position()>1]/span[@class='s2']/a",
			"book_mainpage_xpath":	"//div[@class='search-list']/ul/li[position()>1]/span[@class='s2']/a/@href",
			"book_author_xpath":	"//div[@class='search-list']/ul/li[position()>1]/span[@class='s4']",
			"enable_chapter_page":	0,
			"chapter_page_xpath":	"",
			"chapter_title_xpath":	"//div[@id='list']/dl/dd[position()>12]/a",
			"chapter_url_xpath":	"//div[@id='list']/dl/dd[position()>12]/a/@href",
			"content_xpath":	"//*div[@id='content']",
			"enable_content_next":	0,
			"content_next_url_xpath":	"",
			"content_next_keyword_xpath":	"",
			"content_next_keyword":	"",
			"book_status_pos":	0,
			"book_status_xpath":	"",
			"book_status_keyword":	""
		}]
}`

我不知道是自己正文解析部分写的有问题还是网站做了什么防盗机制，出现了以下问题，

搜索可以正常搜索到一本书，但是打开时提示加载失败。
可能遇到的问题：
1. 正文解析的格式不对（但是我按照其他的小说网站对比过，也多次尝试，如果真的不对，请大神指教）；
2. 网站做了处理，我网站上一些跳转时，后台发现一个整10秒的延迟后才开始加载，但是我在工具中打开时，响应时间明显少于十秒，所以猜测可能是因为程序中对于timeout时间的设置短于网站的线程睡眠时间10秒钟。

最后感谢大佬制作出如此牛逼简洁并富有正义感的摸鱼神器，
爱你。

**Comment by HillsonLiu** [comment]
真是太感谢了，可以在线看章节了，但是又碰到了另一个问题，

有些章节在网站上是以图片格式呈现的，在线小说无法加载这个正常，但是似乎碰到图片章节以后，没办法跳过，就卡在这了。
