### ISSUE TITLE
按F12隐藏边框后，字体会变得很粗

### ISSUE THREAD

**Issue by lovitus** [binbyu/Reader#119]
调整好了字体以后， 按下F12， 字体会变粗。 阅读时会很明显。
未找到相关的设置。

**Comment by Saeviome** [comment]
是不是开了mactype渲染？
如过开了，在mactype的详细信息里关闭对应进程的渲染就可以了。
也可以在配置文件里添加过滤。

**Comment by lovitus** [comment]
> 是不是开了mactype渲染？ 如过开了，在mactype的详细信息里关闭对应进程的渲染就可以了。 也可以在配置文件里添加过滤。

排除好没有问题了. 谢谢.
