### ISSUE TITLE
希望能单独设置章节标题的格式

### ISSUE THREAD

**Issue by Youxikong** [binbyu/Reader#121]
rt。章节标题在正文里面不是很显眼。

**Comment by binbyu** [comment]
在已经发布的Reader v2.0上面已经支持。
设置>显示设置>章节字体

**Comment by Youxikong** [comment]
打开网络书籍的时候，章节标题和正文都设置为了章节标题的字体格式。
![image](https://user-images.githubusercontent.com/26603498/168459316-f203fee7-29e3-41e1-b1cb-947588c07eb5.png)
下图是设置的章节标题和正文的格式。
![image](https://user-images.githubusercontent.com/26603498/168459332-68e21b4b-fb91-4392-8b1b-b7cab202a13c.png)

**Comment by binbyu** [comment]
hi Youxikong,
2.0版本测试不充分。在线书籍，关闭程序，第二次打开时会有此问题。
现已修复，请重新下载。

Thanks,
Binbin

**Comment by Youxikong** [comment]
非常感谢。
