### ISSUE TITLE
打开epub时丢失了前几章

### ISSUE THREAD

**Issue by HephaistosII** [binbyu/Reader#125]
不知为何这本小说在此阅读器打开时会丢失前几章
目录和内容都没有

![微信截图_20220506145009](https://user-images.githubusercontent.com/26473064/167081399-796064ca-6926-446c-888e-8960d7abcbab.png)
![1651819833(1)](https://user-images.githubusercontent.com/26473064/167081411-9594790c-e3d8-46ed-b3cc-fbbeca8edd2f.png)
[哥布林杀手+1.zip](https://github.com/binbyu/Reader/files/8638110/%2B1.zip)

**Comment by binbyu** [comment]
hi ，
感谢反馈。
Reader的epub支持很简陋。这个epub格式比较特别导致章节丢失。
我空闲时会尝试修复此问题。
请给我一个邮箱，改好后我邮件发你。

Thanks,
Binbin

**Comment by HephaistosII** [comment]
> hi ， 感谢反馈。 Reader的epub支持很简陋。这个epub格式比较特别导致章节丢失。 我空闲时会尝试修复此问题。 请给我一个邮箱，改好后我邮件发你。
> 
> Thanks, Binbin

1125605959@qq.com
感谢作者! Reader确实是在工作中帮了我大忙了
