### ISSUE TITLE
2.0遇到的问题

### ISSUE THREAD

**Issue by ScorpioNO** [binbyu/Reader#129]
同样的关键词“这个道士”，都是在“御书网”搜索，1.10可以搜索到结果，但2.0却提示没有，然后存在加载章节白屏的问题，点击新章节之后，界面白屏，无新内容展现，需要再点击一次内容框，才会出现，不管是点击目录还是正常阅读进入下一章都会出现

**Comment by binbyu** [comment]
hi, 没有问题了吗？
我看已经closed了

**Comment by ScorpioNO** [comment]
有一个问题，切换章节的时候，会出现白屏，需要再点击一下才会刷新出来内容



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BinBin ***@***.***&gt;; 
发送时间: 2022年5月12日(星期四) 上午9:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [binbyu/Reader] 2.0遇到的问题 (Issue #129)





 
hi, 没有问题了吗？
 我看已经closed了

**Comment by binbyu** [comment]
看上去是一个致命bug，是100%复现吗？
可以提供一下复现方法吗？

**Comment by binbyu** [comment]
你是 否勾选了“章前分页“，并且没有勾选”压缩空行“？

“章前分页“ 2.0新增的新功能，每一个新的章节在新的一页刷新。
如果没有勾选”压缩空行“，并且前面一章结尾有空行，当这个空行刚好前一页放不下，出现在第二页时，就会出现一此 切换章节前空白页面。
