### ISSUE TITLE
请问此项目基于什么开源协议?

### ISSUE THREAD

**Issue by 351768593** [binbyu/Reader#137]
看到项目里并没有提供 LICENSE 文件或在 readme 等地方声明源码基于哪种协议开源, 请问作者有没有准备添加一下?

**Comment by binbyu** [comment]
我记得，没有LICENSE文件，版权要求是最高的。
请问你是需要用我的代码做什么吗？

**Comment by 351768593** [comment]
没准备干啥, 好奇而已..
非要说的话就是来学习一下

**Comment by binbyu** [comment]
clone和fork，学习是可以的。

**Comment by 351768593** [comment]
好的, 明白了
多谢作者为 ~~摸鱼~~ 开源社区做出的贡献 😆
