### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by gjmhmm8** [binbyu/Reader#175]
建议增加小说背景透明功能，像显示歌词那样显示，同时可加一些混淆视听的文本，比如工作报告，名人名言之类的

**Comment by gjmhmm8** [comment]
书源配置建议增加json解析功能

**Comment by binbyu** [comment]
1. 建议增加小说背景透明功能
已有此功能，详见软件包内readme.txt
2. 书源配置建议增加json解析功能
v2.0.0.3版本对书源的解析，增加了xpath对json的解析。自己手写的，比较简陋。
参考书源：20230821.json

_```
{
	"title":	"笔趣阁xzmncy(json)",
	"host":	"https://www.xzmncy.com",
	"query_url":	"https://www.xzmncy.com/api/search?q=%s",
	"query_method":	0,
	"query_params":	"",
	"query_charset":	1,
	"book_name_xpath":	"/data/search/book_name",
	"book_mainpage_xpath":	"/data/search/book_list_url",
	"book_author_xpath":	"/data/search/author",
	"enable_chapter_page":	0,
	"chapter_page_xpath":	"",
	"chapter_title_xpath":	"//*[@id=\"list\"]/dl/dd/a",
	"chapter_url_xpath":	"//*[@id=\"list\"]/dl/dd/a/@href",
	"enable_chapter_next":	0,
	"chapter_next_url_xpath":	"",
	"chapter_next_keyword_xpath":	"",
	"chapter_next_keyword":	"",
	"content_xpath":	"//*[@id=\"htmlContent\"]/p",
	"enable_content_next":	0,
	"content_next_url_xpath":	"",
	"content_next_keyword_xpath":	"",
	"content_next_keyword":	"",
	"content_filter_type":	0,
	"content_filter_keyword":	""
}
```_

**Comment by gjmhmm8** [comment]
能不能把阅读3的书源支持了
