### ISSUE TITLE
Hope to add a color picker to change the background color

### ISSUE THREAD

**Issue by nikonikoCW** [binbyu/Reader#48]
Hope to add a color picker to change the background color

**Comment by binbyu** [comment]
1. color picker for background color is already exist.
Menu > 设置 > 背景颜色
![image](https://user-images.githubusercontent.com/16300473/103324322-05e48b80-4a82-11eb-8448-72d6e5a77893.png)

2. color picker for font color, I have uploaded a new version today, please download
链接: https://pan.baidu.com/s/1w4f_xGrSWvpjGIGED6dnkA
提取码: v65a

**Comment by nikonikoCW** [comment]
tks
