### ISSUE TITLE
新版本，上/下N行功能，这个N无法自定义

### ISSUE THREAD

**Issue by pigeon-coo** [binbyu/Reader#59]
在旧版本（如1.8.2）中，快捷键设置的上/下N行，这个N跟随自动翻页里的文本滚动速度（X行）而变，虽然有点反直觉，不过也算是有办法配置。
在新版本（如1.9.1）中，自动翻页设置逻辑改变，原本可以自选的X行，只剩单行/双行/三行/整页四个选项，间接导致上/下N行的N无法自由配置。
建议单独提供上/下N行中，N的自由配置。

/*因为我每次翻页，喜欢保留上一页最后一行，便于上下文语义衔接（一般阅读软件都有类似功能），新版本出来之后此功能缺失，只能停留在旧版本。*/

谢谢！

**Comment by binbyu** [comment]
这个遗留上一页多少行的功能设置叫啥名字？
我一会更新下这个功能

**Comment by binbyu** [comment]
hi,
已经更新此功能，请下载最新版本。
使用说明：
设置 > 基本设置 > 保留上页行数

最新release版本：v1.9.1.0
(百度网盘)
链接: https://pan.baidu.com/s/1uRncUXFaKyyHCztgYVQJow
提取码: bfyr

Thanks,
Binbin

**Comment by pigeon-coo** [comment]
没及时看到你的回复，没想到这么高效就搞定了。
非常感谢你的摸鱼阅读器，我已经用它摸了不低于20M TXT的小说了哈哈哈。
