### ISSUE TITLE
建议&bug

### ISSUE THREAD

**Issue by pujie1216** [binbyu/Reader#7]
首先软件小巧,秒开大txt,没有花里胡哨

bug
打开txt后退出,再次打开会有两个View,其中一个点击无反应
![2](https://user-images.githubusercontent.com/21360598/68119697-545dcf00-ff3e-11e9-8c43-0d7dd7f179ed.png)

建议
1.About里加入Github主页或者获取更新的网址
2.加入拖拽功能
3.加入类似老板键的隐藏功能,并非类似Alt+Esc后台化窗体

**Comment by binbyu** [comment]
最新release版本：v1.2.0.0
(百度网盘)
链接: https://pan.baidu.com/s/1TZbU0F5qLe53ggoru5LKfQ
提取码: qj6i




# v1.2.0.0 2019/11/05 功能更新
1. 新增热键支持 1.1 Alt + T ：窗口置顶/取消置顶
1.2 Alt + H ：窗口隐藏/显示
1.3 支持热键修改：setting > config
1.4 热键支持两键组合 和 三键组合
1.5 如果发现默认按键(1.1)无效，说明该热键已经被占用，请参照1.3修改热键
2. 新增章节快速跳转
2.1 ctrl + → ：跳转到下一章节
2.1 ctrl + ← ：跳转到上一章节
3. 支持文件拖拽打开
3.1 仅支持单个txt文件操作
4. 修改再次打开程序会出现两个view的bug


建议很好！
请试用，抽空开发的，没有仔细测试。
