### ISSUE TITLE
书源无法正常搜索

### ISSUE THREAD

**Issue by ceh-ylhy** [binbyu/Reader#78]
“斋书院”书源无法正常搜索，望修复

**Comment by ceh-ylhy** [comment]
要是能使用app【阅读】的书源就好了，作者可以了解下。该软件是安卓端开源软件，其中的书源大多为网友制作，并且量多

**Comment by binbyu** [comment]
刚试了，没有发现问题。
测试关键字：雪中
可以正常搜索，并打开小说。
斋书院好像搜索的时候，关键字不要使用全名，如果搜索结果只有一条时，会有一些问题。
所以：比如需要搜索《雪中悍刀行》，请使用关键字“雪中”

最近工作忙没有时间维护，安卓阅读的书源我还没有仔细研究。后续会尝试下。
Thanks,
Binbin

**Comment by yrChan** [comment]
现在好像搜索的话，都能搜索，就是不能正常打开，不知道是不是就我这样。等作者忙完处理

**Comment by yrChan** [comment]
关注了微信公众号，发现修复了一些书源，谢谢作者
