### ISSUE TITLE
你的更新不要直接去掉上个版本的功能撒

### ISSUE THREAD

**Issue by yangkile** [binbyu/Reader#9]
习惯了那个版本突然更新一脸懵...

滚轮直接翻页 和滚轮饭行都是很好的功能

建议新增的功能你添加在设置里面做配置让用户自己选择

不要直接去除

本来想自己改...但是C++写 win32程序看着太懵了...对应不上来...

**Comment by binbyu** [comment]
哈哈。




置顶：
原来是热键，现在改为了Ctrl+T（非热键），必须先focus界面，才能使用。


滚轮直接翻页：
这个发布前是考虑过的。
在setting &gt; config 里面可以把“文本滚动速度”调整到最大，就可以直接翻页（一滚一整页）。如下图：







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yangkile"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 下午2:59
收件人:&nbsp;"binbyu/Reader"<Reader@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[binbyu/Reader] 你的更新不要直接去掉上个版本的功能撒 (#9)




习惯了那个版本突然更新一脸懵...
 
置顶和滚轮直接翻页都是很好的功能
 
建议新增的功能你添加在设置里面做配置让用户自己选择
 
不要直接去除
