### ISSUE TITLE
能不能在换章节的时候  新的章节不要直接跳到第一行

### ISSUE THREAD

**Issue by byludy** [binbyu/Reader#92]
在看的时候，到新的一张，能不能接着从底部出来？
因为习惯看的时候一直按  ↓         然后旧的没看完，新的章节来了就直接跳到第一行，很麻烦，又要回头看

**Comment by binbyu** [comment]
Reader没有新的章节直接跳到第一行的功能。都是接着重底部出来。
请还原默认设置，试试看

**Comment by byludy** [comment]
![112](https://user-images.githubusercontent.com/56289598/130207735-5b54e87e-6a31-42bb-b195-a668bc69d66f.gif)
录了个gif 不论还原默认设置还是重新下载新的软件，都是这样
操作里面我的操作就是 按 上下左右的 下↓ 到新的一章，不能继续接在下面，而是跳到第一行

**Comment by binbyu** [comment]
已经复现，是有个bug。
后续我空闲是会修复

**Comment by byludy** [comment]
感谢  我以为是我自己的问题

**Comment by byludy** [comment]
> 已经复现，是有个bug。
> 后续我空闲是会修复

能不能提供一个没这个BUG的版本号，我下一个

**Comment by binbyu** [comment]
你发个邮件到我的邮箱binbyu@qq.com，
我一会修复一下发你邮箱

**Comment by byludy** [comment]
发了 gmail

**Comment by binbyu** [comment]
已提供附件版本，请试用。

**Comment by byludy** [comment]
使用中，没有问题了
